### ISSUE TITLE
Usage at Wix

### ISSUE THREAD

**Issue by ngarnier** [wix-incubator/mjml-react#10]
Hello guys, Nico from the MJML/Mailjet team here! 

I love seeing that you built a lib on top of MJML at Wix. I suppose you are using it in a product, is it available already? Would love to see the final result as it's always exciting to see what's built with MJML!

Cheers!

**Comment by mastertheblaster** [comment]
Hi @ngarnier,

Sorry for the long delay. And yes we do use it inside our project.
So the quickest way to see it, would be:

1. Create an account inside `Wix`
2. Create a website
3. Open website settings
4. Choose `Marketing Tools --> Email Marketing` and give it a try.

PS. Because this feature is still experimental - once you create an account, please let us know your email (you used for account creation), so we could enable this experiment for your account.

And your tool is great!

**Comment by ngarnier** [comment]
hey @mastertheblaster, no worries! I created an account, you can give access to ngarnier@mailjet.com :-).

**Comment by mastertheblaster** [comment]
Done. You account is welcome for a test drive :)

**Comment by ngarnier** [comment]
Thanks a lot! It looks very nice, I love the simple layout and easiness of use. 

I'll close the issue :-)
