### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by nicksarafa** [wix-incubator/mjml-react#27]
Hey guys!

I'm looking to integrate my emails, front end web, and front end native mobile apps through global stylesheets using the react ecosystem, and styled components. This library seems to, in theory solve my issue for the email part! I have a couple questions..

1. Are any companies using this library in production?
2. When you say `requires a node` do you mean the end result isn't static HTML which can be popped into something like send grid and sent as HTML emails?
3. Is the output the same as the standard MJML library? If not, is there a way we can configure the output to be the same as the standard library, from the react components?

Thank you for all the hard work!
Nick

**Comment by kranux** [comment]
Hi, thanks for your interest in mjml-react!

1. Yes, we, Wix.com use this library in prod since Jun 2018.
2. End result of this library is static HTML, note that it's generated on server side.
3. Yes, output is the same, as the standard Mjml, as this is just a React wrapper around Mjml.

Happy to help! :)
