### ISSUE TITLE
Incorrect typings for MjmlText when used in header

### ISSUE THREAD

**Issue by mullwaden** [wix-incubator/mjml-react#32]
Hello,
I am getting a minor typescript error when using MjmlText in the header as in this case no child element is provided or needed. 

```
<MjmlHead>
  <MjmlAttributes>
    <MjmlText font-size="16px" />
  </MjmlAttributes>
</MjmlHead>
```

The above code gives a TS error as no child is provided to MjmlText. However I believe the code is the correct way to set general styling on all mjmlText items.

I could make a pr to make children an optional prop but it doesnt feel like the right solution. So any help much appreciated

**Comment by kranux** [comment]
Hi, 

maybe you can pass something empty into `<MjmlText>` as a temp workaround? like `<div />`

BTW, why optional child does not seem as a right solution?

**Comment by CarsonF** [comment]
This works for me:
```tsx
<MjmlAttributes>
  <MjmlText lineHeight="1.5">{}</MjmlText>
</MjmlAttributes>
```

**Comment by osdiab** [comment]
Thanks for the workaround @CarsonF !

FYI, I don't think this is the correct place to leave the issue, since the types are on `DefinitelyTyped` and not managed by this repo. But, for the sake of continuing the discussion where it can be easily found:

I'm just getting started with this library but I'm pretty sure TypeScript can't change the type of an object dependent on where it's being used. As such I see a couple options to support this out of box.

1. don't force children to be there (which I don't think would be invalid MJML?)
1. add a generic or a flag prop to explicitly signal that this is being used in the context of the `MjmlHead` element, and therefore don't force the children prop

In my case though I'm just going to opt for @CarsonF 's solution, handle it with wrapper React components that apply the styles independently.
